### ISSUE TITLE
Money in inventory

### ISSUE THREAD

**Issue by withoutchiu** [hsnnnnn/hsn-inventory#2]
Hi im wondering if this inventory should display money? On my end, it doesnt.

**Comment by hsnnnnn** [comment]
you can add money like item, if you don't know what to do contact with me on discord

**Comment by withoutchiu** [comment]
Hi thanks for reply. Can i have your discord id? Could it be possibly commit into this master so that everyone can have it as well?

**Comment by hsnnnnn** [comment]
https://discord.gg/6FQhKDXBJ6
