### ISSUE TITLE
cant open iventory

### ISSUE THREAD

**Issue by DNDdjay** [hsnnnnn/hsn-inventory#22]
hii

i have done the setup but i cant open the inventory 
and i dont get any errors

**Comment by Ruqen** [comment]
What key are you pressing?
If F2, are you sure you don't get any errors?

**Comment by DNDdjay** [comment]
yes i pressing F2  and i dont get any errors

**Comment by NazriGenfil** [comment]
did you change the resource name?

**Comment by DNDdjay** [comment]
yes i removed the -main
